version: "3.7"
services:
  server:
    build: ./server
    container_name: server-c
    ports:
      - "4000:4000"
    volumes:
      - ./server:/app
      - ./app/node_modules
  client:
    build: ./client
    container_name: client-c
    ports:
      - "3000-3000"
    volumes:
      - ./client:/app
      - ./app/node_modules
