# parent layer
FROM node:18-alpine

# for dev pupose only 
RUN npm install -g nodemon

# create directory
WORKDIR /app


# copy all depentancies
COPY package.json ./

# install the depentancies
RUN npm install

#copy our sorce codes and store in new folder "app"
COPY . .

#port 
EXPOSE 4000

#execute command
CMD ["npm","run","dev"]
